services:
  db:
    container_name: reportia_postgres
    environment:
      POSTGRES_DB: reportia
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      timeout: 5s
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./backend/migrations:/docker-entrypoint-initdb.d:ro
